version: '3'
services:
  video_scraper:
    image: shenxianmq/video_scraper:latest
    volumes:
      - ./config:/app/config
      - ./downloads/telegram:/app/downloads/telegram
      - ./downloads/youtube:/app/downloads/youtube
      - ./downloads/temp:/app/temp

    restart: unless-stopped
    container_name: video_scraper
    environment:
      - TZ=Asia/Shanghai 